export { default as HomeHero } from './HomeHero';
export { default as HomeMinimal } from './HomeMinimal';
export { default as HomeDarkMode } from './HomeDarkMode';
export { default as HomeLookingFor } from './HomeLookingFor';
export { default as HomeOurProduct } from './HomeOurProduct';
export { default as HomePricingPlans } from './HomePricingPlans';
export { default as HomeAdvertisement } from './HomeAdvertisement';
export { default as HomeCleanInterfaces } from './HomeCleanInterfaces';
export { default as HomeHugePackElements } from './HomeHugePackElements';
export { default as HomeOurFeature } from './HomeOurFeature';
export { default as HomeOurProject } from './HomeOurProject';
export { default as HomeInegrateApp } from './HomeInegrateApp';
export { default as HomeOurService } from './HomeOurService';
export { default as HomeDownloadMobile } from './HomeDownloadMobile';
export { default as HomeCustomerSupport } from './HomeCustomerSupport';
export { default as HomeProjectStory } from './HomeProjectStory';
export { default as HomeContactUs } from './HomeContactUs';
export { default as HomeFreeTrial } from './HomeFreeTrial';

